/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMailboxRouteImport } from './routes/_app/$mailbox'
import { Route as AppMailboxIndexRouteImport } from './routes/_app/$mailbox.index'
import { Route as AppMailboxMessageIdRouteImport } from './routes/_app/$mailbox.$messageId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMailboxRoute = AppMailboxRouteImport.update({
  id: '/$mailbox',
  path: '/$mailbox',
  getParentRoute: () => AppRoute,
} as any)
const AppMailboxIndexRoute = AppMailboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMailboxRoute,
} as any)
const AppMailboxMessageIdRoute = AppMailboxMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => AppMailboxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$mailbox': typeof AppMailboxRouteWithChildren
  '/$mailbox/$messageId': typeof AppMailboxMessageIdRoute
  '/$mailbox/': typeof AppMailboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$mailbox/$messageId': typeof AppMailboxMessageIdRoute
  '/$mailbox': typeof AppMailboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/$mailbox': typeof AppMailboxRouteWithChildren
  '/_app/$mailbox/$messageId': typeof AppMailboxMessageIdRoute
  '/_app/$mailbox/': typeof AppMailboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$mailbox' | '/$mailbox/$messageId' | '/$mailbox/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$mailbox/$messageId' | '/$mailbox'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/$mailbox'
    | '/_app/$mailbox/$messageId'
    | '/_app/$mailbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$mailbox': {
      id: '/_app/$mailbox'
      path: '/$mailbox'
      fullPath: '/$mailbox'
      preLoaderRoute: typeof AppMailboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$mailbox/': {
      id: '/_app/$mailbox/'
      path: '/'
      fullPath: '/$mailbox/'
      preLoaderRoute: typeof AppMailboxIndexRouteImport
      parentRoute: typeof AppMailboxRoute
    }
    '/_app/$mailbox/$messageId': {
      id: '/_app/$mailbox/$messageId'
      path: '/$messageId'
      fullPath: '/$mailbox/$messageId'
      preLoaderRoute: typeof AppMailboxMessageIdRouteImport
      parentRoute: typeof AppMailboxRoute
    }
  }
}

interface AppMailboxRouteChildren {
  AppMailboxMessageIdRoute: typeof AppMailboxMessageIdRoute
  AppMailboxIndexRoute: typeof AppMailboxIndexRoute
}

const AppMailboxRouteChildren: AppMailboxRouteChildren = {
  AppMailboxMessageIdRoute: AppMailboxMessageIdRoute,
  AppMailboxIndexRoute: AppMailboxIndexRoute,
}

const AppMailboxRouteWithChildren = AppMailboxRoute._addFileChildren(
  AppMailboxRouteChildren,
)

interface AppRouteChildren {
  AppMailboxRoute: typeof AppMailboxRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppMailboxRoute: AppMailboxRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
