/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceRouteImport } from './routes/_app/workspace'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppDropRouteImport } from './routes/_app/drop'
import { Route as AppMailboxRouteImport } from './routes/_app/$mailbox'
import { Route as AppWorkspaceIndexRouteImport } from './routes/_app/workspace.index'
import { Route as AppMessagesIndexRouteImport } from './routes/_app/messages.index'
import { Route as AppDropIndexRouteImport } from './routes/_app/drop.index'
import { Route as AppMailboxIndexRouteImport } from './routes/_app/$mailbox.index'
import { Route as AppWorkspaceGeneralRouteImport } from './routes/_app/workspace.general'
import { Route as AppWorkspaceEmailSendersRouteImport } from './routes/_app/workspace.email-senders'
import { Route as AppWorkspaceEmailReceiversRouteImport } from './routes/_app/workspace.email-receivers'
import { Route as AppMessagesConversationIdRouteImport } from './routes/_app/messages.$conversationId'
import { Route as AppDropDropIdRouteImport } from './routes/_app/drop.$dropId'
import { Route as AppMailboxMessageIdRouteImport } from './routes/_app/$mailbox.$messageId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDropRoute = AppDropRouteImport.update({
  id: '/drop',
  path: '/drop',
  getParentRoute: () => AppRoute,
} as any)
const AppMailboxRoute = AppMailboxRouteImport.update({
  id: '/$mailbox',
  path: '/$mailbox',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceIndexRoute = AppWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppDropIndexRoute = AppDropIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDropRoute,
} as any)
const AppMailboxIndexRoute = AppMailboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMailboxRoute,
} as any)
const AppWorkspaceGeneralRoute = AppWorkspaceGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceEmailSendersRoute =
  AppWorkspaceEmailSendersRouteImport.update({
    id: '/email-senders',
    path: '/email-senders',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceEmailReceiversRoute =
  AppWorkspaceEmailReceiversRouteImport.update({
    id: '/email-receivers',
    path: '/email-receivers',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppMessagesConversationIdRoute =
  AppMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AppMessagesRoute,
  } as any)
const AppDropDropIdRoute = AppDropDropIdRouteImport.update({
  id: '/$dropId',
  path: '/$dropId',
  getParentRoute: () => AppDropRoute,
} as any)
const AppMailboxMessageIdRoute = AppMailboxMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => AppMailboxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$mailbox': typeof AppMailboxRouteWithChildren
  '/drop': typeof AppDropRouteWithChildren
  '/messages': typeof AppMessagesRouteWithChildren
  '/workspace': typeof AppWorkspaceRouteWithChildren
  '/$mailbox/$messageId': typeof AppMailboxMessageIdRoute
  '/drop/$dropId': typeof AppDropDropIdRoute
  '/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/workspace/email-receivers': typeof AppWorkspaceEmailReceiversRoute
  '/workspace/email-senders': typeof AppWorkspaceEmailSendersRoute
  '/workspace/general': typeof AppWorkspaceGeneralRoute
  '/$mailbox/': typeof AppMailboxIndexRoute
  '/drop/': typeof AppDropIndexRoute
  '/messages/': typeof AppMessagesIndexRoute
  '/workspace/': typeof AppWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$mailbox/$messageId': typeof AppMailboxMessageIdRoute
  '/drop/$dropId': typeof AppDropDropIdRoute
  '/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/workspace/email-receivers': typeof AppWorkspaceEmailReceiversRoute
  '/workspace/email-senders': typeof AppWorkspaceEmailSendersRoute
  '/workspace/general': typeof AppWorkspaceGeneralRoute
  '/$mailbox': typeof AppMailboxIndexRoute
  '/drop': typeof AppDropIndexRoute
  '/messages': typeof AppMessagesIndexRoute
  '/workspace': typeof AppWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/$mailbox': typeof AppMailboxRouteWithChildren
  '/_app/drop': typeof AppDropRouteWithChildren
  '/_app/messages': typeof AppMessagesRouteWithChildren
  '/_app/workspace': typeof AppWorkspaceRouteWithChildren
  '/_app/$mailbox/$messageId': typeof AppMailboxMessageIdRoute
  '/_app/drop/$dropId': typeof AppDropDropIdRoute
  '/_app/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/_app/workspace/email-receivers': typeof AppWorkspaceEmailReceiversRoute
  '/_app/workspace/email-senders': typeof AppWorkspaceEmailSendersRoute
  '/_app/workspace/general': typeof AppWorkspaceGeneralRoute
  '/_app/$mailbox/': typeof AppMailboxIndexRoute
  '/_app/drop/': typeof AppDropIndexRoute
  '/_app/messages/': typeof AppMessagesIndexRoute
  '/_app/workspace/': typeof AppWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$mailbox'
    | '/drop'
    | '/messages'
    | '/workspace'
    | '/$mailbox/$messageId'
    | '/drop/$dropId'
    | '/messages/$conversationId'
    | '/workspace/email-receivers'
    | '/workspace/email-senders'
    | '/workspace/general'
    | '/$mailbox/'
    | '/drop/'
    | '/messages/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$mailbox/$messageId'
    | '/drop/$dropId'
    | '/messages/$conversationId'
    | '/workspace/email-receivers'
    | '/workspace/email-senders'
    | '/workspace/general'
    | '/$mailbox'
    | '/drop'
    | '/messages'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/$mailbox'
    | '/_app/drop'
    | '/_app/messages'
    | '/_app/workspace'
    | '/_app/$mailbox/$messageId'
    | '/_app/drop/$dropId'
    | '/_app/messages/$conversationId'
    | '/_app/workspace/email-receivers'
    | '/_app/workspace/email-senders'
    | '/_app/workspace/general'
    | '/_app/$mailbox/'
    | '/_app/drop/'
    | '/_app/messages/'
    | '/_app/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drop': {
      id: '/_app/drop'
      path: '/drop'
      fullPath: '/drop'
      preLoaderRoute: typeof AppDropRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$mailbox': {
      id: '/_app/$mailbox'
      path: '/$mailbox'
      fullPath: '/$mailbox'
      preLoaderRoute: typeof AppMailboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/': {
      id: '/_app/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AppWorkspaceIndexRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/messages/': {
      id: '/_app/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/_app/drop/': {
      id: '/_app/drop/'
      path: '/'
      fullPath: '/drop/'
      preLoaderRoute: typeof AppDropIndexRouteImport
      parentRoute: typeof AppDropRoute
    }
    '/_app/$mailbox/': {
      id: '/_app/$mailbox/'
      path: '/'
      fullPath: '/$mailbox/'
      preLoaderRoute: typeof AppMailboxIndexRouteImport
      parentRoute: typeof AppMailboxRoute
    }
    '/_app/workspace/general': {
      id: '/_app/workspace/general'
      path: '/general'
      fullPath: '/workspace/general'
      preLoaderRoute: typeof AppWorkspaceGeneralRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/workspace/email-senders': {
      id: '/_app/workspace/email-senders'
      path: '/email-senders'
      fullPath: '/workspace/email-senders'
      preLoaderRoute: typeof AppWorkspaceEmailSendersRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/workspace/email-receivers': {
      id: '/_app/workspace/email-receivers'
      path: '/email-receivers'
      fullPath: '/workspace/email-receivers'
      preLoaderRoute: typeof AppWorkspaceEmailReceiversRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/messages/$conversationId': {
      id: '/_app/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AppMessagesConversationIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/_app/drop/$dropId': {
      id: '/_app/drop/$dropId'
      path: '/$dropId'
      fullPath: '/drop/$dropId'
      preLoaderRoute: typeof AppDropDropIdRouteImport
      parentRoute: typeof AppDropRoute
    }
    '/_app/$mailbox/$messageId': {
      id: '/_app/$mailbox/$messageId'
      path: '/$messageId'
      fullPath: '/$mailbox/$messageId'
      preLoaderRoute: typeof AppMailboxMessageIdRouteImport
      parentRoute: typeof AppMailboxRoute
    }
  }
}

interface AppMailboxRouteChildren {
  AppMailboxMessageIdRoute: typeof AppMailboxMessageIdRoute
  AppMailboxIndexRoute: typeof AppMailboxIndexRoute
}

const AppMailboxRouteChildren: AppMailboxRouteChildren = {
  AppMailboxMessageIdRoute: AppMailboxMessageIdRoute,
  AppMailboxIndexRoute: AppMailboxIndexRoute,
}

const AppMailboxRouteWithChildren = AppMailboxRoute._addFileChildren(
  AppMailboxRouteChildren,
)

interface AppDropRouteChildren {
  AppDropDropIdRoute: typeof AppDropDropIdRoute
  AppDropIndexRoute: typeof AppDropIndexRoute
}

const AppDropRouteChildren: AppDropRouteChildren = {
  AppDropDropIdRoute: AppDropDropIdRoute,
  AppDropIndexRoute: AppDropIndexRoute,
}

const AppDropRouteWithChildren =
  AppDropRoute._addFileChildren(AppDropRouteChildren)

interface AppMessagesRouteChildren {
  AppMessagesConversationIdRoute: typeof AppMessagesConversationIdRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesConversationIdRoute: AppMessagesConversationIdRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppWorkspaceRouteChildren {
  AppWorkspaceEmailReceiversRoute: typeof AppWorkspaceEmailReceiversRoute
  AppWorkspaceEmailSendersRoute: typeof AppWorkspaceEmailSendersRoute
  AppWorkspaceGeneralRoute: typeof AppWorkspaceGeneralRoute
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceEmailReceiversRoute: AppWorkspaceEmailReceiversRoute,
  AppWorkspaceEmailSendersRoute: AppWorkspaceEmailSendersRoute,
  AppWorkspaceGeneralRoute: AppWorkspaceGeneralRoute,
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppRouteChildren {
  AppMailboxRoute: typeof AppMailboxRouteWithChildren
  AppDropRoute: typeof AppDropRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppMailboxRoute: AppMailboxRouteWithChildren,
  AppDropRoute: AppDropRouteWithChildren,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
